name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # This allows the GITHUB_TOKEN to push changes

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=ACFHarbinger&theme=radical&show_icons=true"
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }} # Use the automatic token

      - name: Generate Language Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=ACFHarbinger&theme=radical&langs_count=15"
          path: profile/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub statistics" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}